name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:lts-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install git
        run: apk add --no-cache git
      - name: Build Web
        run: |
          cd deadlock-item-viewer
          npm install
          npm run build
          mkdir out
          mkdir out/dist

      - name: Copy index
        uses: canastro/copy-file-action@master
        with:
          source: index.html
          target: out/index.html
      - name: Copy dist
        uses: canastro/copy-file-action@master
        with:
          source: dist/.
          target: out/.
          flags: '-r'
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          # Build directory to deploy
          build_dir: out/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}